### ISSUE TITLE
add Ana_4Lep

### ISSUE THREAD

**Issue by gerbaudo** [susynt/SusyNtuple#80]
Don't know whether this name is ok. Ask Mike.

**Comment by mikeflowerdew** [comment]
Hi,

Just spotted this. Ana_4Lep is fine. It should mostly look like Ana_3Lep, with a few modifications:
* Signal electrons have MediumLH and GradientLoose isolation (the latter under discussion, but it's that for now).
* Baseline muons should be accepted up to at least 2.5, even 2.7? (now SUSYTools standard).
* Signal muons have GradientLoose isolation. (should Ana_3Lep really have different isolation for electrons and muons?).
* Harmonised overlap removal (eg the order [here](https://github.com/susynt/SusyNtuple/blob/master/Root/OverlapTools.cxx#L104) does not match the order [here](https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/AnalysisCommon/AssociationUtils/trunk/Root/OverlapRemovalTool.cxx#L75)).

Taus etc are another issue, the above would already be a great start.

How should we proceed? Should I try to fork the master version? I'm new to GitHub, so not exactly sure of what I'm doing.

Tagging @srmaschek, who's actually done all the work so far.
