### ISSUE TITLE
rewrite MCWeighter

### ISSUE THREAD

**Issue by gerbaudo** [susynt/SusyNtuple#83]
Two goals:
- get rid of the obsolete `buildSumwMapFromTree()` and `buildSumwMapFromChain()`
- parse ourselves the cross section files, avoiding `SUSY::CrossSectionDB()`
  and its weird access methods and default values

**Comment by dantrim** [comment]
@gerbaudo we should really tackle this. And also see if there has been any headway on getting the per-sub-process sumw from the derivations.

**Comment by gerbaudo** [comment]
Also make sure we stop when the xsec is missing, rather than returning -1.
The only special case should be for multi-process signal samples, where
we might want to return 0 for unknown (rare) processes (but in this case
it should print a summary)

**Comment by dantrim** [comment]
done!
