### ISSUE TITLE
add photons to selectoObjects()

### ISSUE THREAD

**Issue by dantrim** [susynt/SusyNtuple#92]
Currently we only build up the vectors for pre-, base-, and signal- leptons, jets, and taus [1]. 

We should build up the corresponding photon vectors.

Additionally, the default SUSY OR procedures now involve both photons and taus [2].

[1] https://github.com/susynt/SusyNtuple/blob/master/Root/SusyNtAna.cxx#L247
[2] https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/AnalysisCommon/AssociationUtils/trunk/Root/OverlapRemovalTool.cxx#L84

**Comment by mikeflowerdew** [comment]
The last point is actually incorrect, analysers have to turn on photon and/or tau overlap removal explicitly. Analyses using neither type of object have them off by default:
https://svnweb.cern.ch/trac/atlasoff/browser/PhysicsAnalysis/SUSYPhys/SUSYTools/trunk/data/SUSYTools_Default.conf#L67

Having said that, in 4L we a) definitely want tau OR on by default, and b) will need photon OR at least in some CRs (for the SRs the question is more subtle and still to be debated).

**Comment by dantrim** [comment]
Hi @mikeflowerdew thanks for pointing this out. Essentially what I mean is to just provide the photon vector to the "performOverlap" method of the overlapTool. As the overlapTool will be already configured for the given AnalysisType, internally it will perform the correct OR procedure of your AnalysisType's overlapTool or you can configure it to be the one you require. Right now, photons are not considered at all, at least within SusyNtAna.
